# Generated by Django 3.2.8 on 2021-10-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_auto_20211007_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2021-05-05'),
            preserve_default=False,
        ),
    ]
